### ISSUE TITLE
Where are the api-url options?

### ISSUE THREAD

**Issue by serhioV** [jagdeep-singh/angularMultipleSelect#38]
Hello, 

How do I manage the api-URL options
```
        <multiple-autocomplete ng-model="peopleFromApi"
                               object-property="name"
                               api-url="/api/myApi"
                               api-url-options="???"
```

And where there is a codepen/jsfiddle for the documentation (the link provided in the doc does not display sources) ?

**Comment by jagdeep-singh** [comment]
Hi Serhio,
Thanks for using this. I have added "api-url-option". And the format of this as below : 
<multiple-autocomplete ng-model="skillsFromApi"
                               api-url="/api/myApi"
                                api-url-option="apiUrlOption">
**And in controller as below :** 
apiUrlOption = {
            method : "GET",
            responseInterceptor : function (response) {
                /*
                *
                * Process response acc. to your requirement.
                * After processing we are assuming "response.data" as "suggestionsArr".
                *
                * */
            }
        }

If you need anything else please do let me know.
